### ISSUE TITLE
Rename repo as a general place for co-op meeting notes and documents

### ISSUE THREAD

**Issue by dcwalk** [hyphacoop/december-retreat#23]
We should update the name of this repo to reflect what we actually keep here:

- all notes?
- retreat items
- milestones??
- other important docs?

**Comment by benhylau** [comment]
`organizing`?

**Comment by dcwalk** [comment]
sure.
maybe `documents` or `filing cabinet` if we see this as a more of just a place for notes rather than a "living" repo we coordinate from?

**Comment by patcon** [comment]
- :heart: I feel that `filing cabinet` might not seem "active"
- :heart: I feel that `documents` captures what's here now, but might be too restrictive.
- :heart: I feel `organizing` is the most all-encompassing.
- :bulb: Other options:
  - `meta` ([@coala/meta](https://github.com/coala/meta) does this),
  - `overview` (EDGI did this),
  - `corporate` (tongue-in-cheek, @badideafactory does this)
  - `hyphacoop`

**Comment by dcwalk** [comment]
Happy with `organizing` or `meta` if we see this as an active place :+1:

**Comment by patcon** [comment]
Seems like we're ok with `organzing`, so going to close this out and make that change :)

**Comment by patcon** [comment]
Pinned it in github org: https://github.com/hyphacoop
